### ISSUE TITLE
mtu1280 IPv6 address used for outgoing connections

### ISSUE THREAD

**Issue by jm493** [falling-sky/mtu1280d#1]
### Problem: 
The mtu 1280 interface might be used for outgoing connections from the server, e.g. when mirror sites refresh their content.

Test which IPv6 address is being used by
```
wget -q -O- -6 http://download.aditsystems.com/ip.php
```

[http://www.davidc.net/networking/ipv6-source-address-selection-linux]
> "If the eight rules fail to choose a single address, some unspecified tie-breaker should be used." Linux chooses to use the latest address added.

Normally, it would be the extra IPv6 address with mtu 1280  that is added last

### Ways to change selection order:
http://biplane.com.au/blog/?p=30
> TECHNIQUE ONE: DEPRECATE THE ADDRESSES YOU DON’T WANT SELECTED
> TECHNIQUE TWO: MODIFY THE LABEL TABLE
> TECHNIQUE THREE: PREFER PRIVACY ADDRESSES

Or have the preferred, native mtu IPv6 address to be the last one defined.

### For Debian systems
[https://github.com/falling-sky/source/wiki/InstallPMTUD]
has the mtu 1280 address configured before the normal address.  Should be OK.
```
iface eth0 inet6 static
 address 2001:db8:1:18::119
 netmask 64
 gateway 2001:db8:1:18::1
 pre-up /sbin/ifconfig eth0 inet6 add 2001:db8:1:18::1280/64 
 pre-down /sbin/ifconfig eth0 inet6 del 2001:db8:1:18::1280/64
```
Or could deprecate the address [http://www.davidc.net/networking/ipv6-source-address-selection-linux]
```
iface eth0 inet6 static
 address 2001:db8:1:18::119
 netmask 64
 gateway 2001:db8:1:18::1
 up /sbin/ifconfig eth0 inet6 add 2001:db8:1:18::1280/64 preferred_lft 0
```

### Red Hat
A similar trick in `/etc/sysconfig/network-scripts/ifcfg-eth0` would be to have the mtu 1280 address as the "normal" address, and the native mtu address as the secondary address.
```
IPV6INIT=yes
IPV6ADDR=2001:db8:1:18::1280
IPV6ADDR_SECONDARIES=2001:db8:1:18::119
```
Seems like a hack to me.

There doesn't seem to be any way to tune the line in `/etc/sysconfig/network-scripts/network-functions-ipv6`
```
/sbin/ip -6 addr add $address dev $device
```
to e.g. force `preferred_lft 0` or to run extra commands.

So, will probably will have to add something to /etc/rc.local
e.g.
```
/sbin/ip -6 addr change 2001:db8:1:18::1280 dev eth0 preferred_lft 0
```

**Comment by jfesler** [comment]
Good catch with the source address selection issue.  It would suck if the places you try and fetch updates from had broken PMTUD *and* you were triggering PMTUD.

I've updated the wiki; now only the /etc/rc.local method is documented.
This is now consistent across OS's and simplified to 

ip -6 addr add 2001:db8:1:18::1280 dev eth0 preferred_lft 0
